layout_spectrum: 0.5105130723677576
typography_spectrum: 0.416134730912745
color:
  brandStrength: 0.8279786163475364
  lightness: 0.4570630663074553
  saturation: 0.0514647108502686
  rhythmicContrast: 0.816791663877666
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: TOTH
description: Reimagining Healthcare
